baseURL = "https://ecsworkshop.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amazon ECS Workshop"
theme = "learn"
uglyurls = true
googleAnalytics = "UA-44634850-2"

[blackfriday] 
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Brent Langston"
description = "Amazon ECS Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true

[[menu.shortcuts]]
name = "<i class='fa fa-twitter fa-lg'></i> @brentContained"
identifier = "tw"
url = "https://twitter.com/intent/user?screen_name=brentContained"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
